// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using FlightHistoryScraper.Json;
//
//    var radarArea = RadarArea.FromJson(jsonString);

using Newtonsoft.Json;
using System.Collections.Generic;

namespace FlightHistoryScraper.Json
{
    public static class SerializeBase
    {
        public static string ToJson(this Flight self) => JsonConvert.SerializeObject(self, FlightHistoryScraper.Json.ConverterBase.Settings);
        public static string ToJson(this Dictionary<string, RadarAreaValue> self) => JsonConvert.SerializeObject(self, FlightHistoryScraper.Json.ConverterBase.SettingsRadar);
    }
}