// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using FlightRaderScrape.Json;
//
//    var radarArea = RadarArea.FromJson(jsonString);

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Globalization;

namespace FlightRaderScrape.Json
{
    internal static class ConverterBase
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
        public static readonly JsonSerializerSettings SettingsRadar = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                RadarAreaValueConverter.Singleton,
                RadarAreaElementConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}